### ISSUE TITLE
hello sir your github pages is not working it only shows your readme please fix thanks

### ISSUE THREAD

**Issue by Miraii133** [shunindesuuu/Coffee-Website#1]
read title

**Comment by shunindesuuu** [comment]
> read title

Need daw ug index.html but ours is index.php

Sad pepega

**Comment by Miraii133** [comment]
Apparently github pages only supports static pages so PHP and other dynamic scriptings are off its functionalities
https://stackoverflow.com/questions/27672315/do-github-pages-support-php

Closing this now
